### PR TITLE
Fix Delphi issues

### PR DESCRIPTION
**Pull request by suve**
This patch aims to fix Delphi-related issues: #103 and #91.

@achinastone could you please try out this patch and tell me if it works as intended? I do not have a Delphi installation at hand to try it out myself.

### CODE REVIEW

**Comment by achinastone** [comment]
_(Compile success after some little change:
**add then follow**  
  pcint = ^cint;
  pcuint = ^cuint;
 )_

**It has some new problem:**
[dcc32 Error] sdlpower.inc(32): E2003 Undeclared identifier: 'pcint'
[dcc32 Error] sdlpower.inc(32): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlthread.inc(148): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlpixels.inc(481): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrect.inc(109): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(855): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(882): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(900): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(929): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(958): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(1485): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlvideo.inc(1536): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlmessagebox.inc(98): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(188): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(237): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(237): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(376): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(468): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(595): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlrenderer.inc(916): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlkeyboard.inc(71): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlmouse.inc(68): E2005 'pcint' is not a type identifier
[dcc32 Error] sdlmouse.inc(119): E2005 'pcint' is not a type identifier
[dcc32 Error] sdljoystick.inc(908): E2005 'pcint' is not a type identifier
[dcc32 Error] sdljoystick.inc(908): E2005 'pcint' is not a type identifier

**Comment by suve** [comment]
Right-o, I forgot about the pointer types. Fixed by e8b7aa821f5ad6c2e66d59377da46a018d281d43.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
@achinastone Does the last commit #e8b7aa8 fix the issue?

Best regards

**Comment by Free-Pascal-meets-SDL-Website** [comment]
It looks good and should work for Delphi users. Thanks!

**Pull request merged**
