### PR TITLE
Added all missing double-pointer types in all source files

### PR DESCRIPTION
**Pull request by furious-programming**

### CODE REVIEW

**Review by Free-Pascal-meets-SDL-Website — APPROVED** [review]
First off, thanks a lot for this update which improves the units by a great margin.

Some ideas though:

- the merge-commit #[4dc9bad](https://github.com/PascalGameDevelopment/SDL2-for-Pascal/pull/122/commits/4dc9bad1a0f29634324fcd5f43738623ea080940) could have been prevented if the latest development state of the units would have been used
- for review, tracking possible issues, and reverting undesired changes it makes life a lot easier if the changes are split over several commit instead of one large commit (I guess you used some algorithm for the updates - but even then it would be preferable to have the commits file by file or something)
- I'm undecided about the double pointer types in ctypes.inc (e. g. `ppcbool`) because there is no counter-part in ctypes.pas (still approved form my side for the moment)

**Comment by furious-programming** [comment]
When it comes to GitHub, and especially contributing to open source, I have two left hands — I don't really understand how to click it correctly, so it's a big success anyway that the repository is still working. :)

**Comment by suve** [comment]
Ehh. Personally I'm really not a fan of this, but let's not repeat the discussion from #105 all over again.

There are some places where the indentation doesn't match, but if @Free-Pascal-meets-SDL-Website doesn't mind, I can merge this and fix misaligned places.

**Comment by furious-programming** [comment]
Indentations match everywhere, according to the types they are pointers to. I've checked this in both the IDE and GitHub.

> Ehh. Personally I'm really not a fan of this, but let's not repeat the discussion from #105 all over again.

Even if these types are not used by headers, they will definitely be used by header users. The longer I developed my game code, the more double pointers I missed. Why would I declare them myself in the game code, when these types are strictly headers-related and should be provided by them? Well, that's why it's definitely better to include them in the headers and let everyone use what they need. At least these types will be properly declared and will always match the base header types.

If more types are added to the headers in the future, I suggest declaring a single and a double pointer twice for each. This way the headers will be fully usable and well organized, which is very important.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
> There are some places where the indentation doesn't match, but if @Free-Pascal-meets-SDL-Website doesn't mind, I can merge this and fix misaligned places.

Damn, missed these, saw them just on second inspection! Great job! I guess @furious-programming should have the chance to fix this as this is his/her PR.  

> Indentations match everywhere, according to the types they are pointers to. I've checked this in both the IDE and GitHub.

There are some mismatching indentations, see e. g. `TSDL_SpinLock`. Could you fix them, please.

>If more types are added to the headers in the future, I suggest declaring a single and a double pointer for each of them. This way the headers will be fully usable and well organized, which is very important.

Please add as new fifth point (right before the point that links to the Tranlsation Cheat Sheet) in section Code style guidelines: _For convenience we encourage to add single and double pointers for any SDL type. (See #105)_

**Comment by furious-programming** [comment]
> There are some mismatching indentations, see e. g. `TSDL_SpinLock`. Could you fix them, please.

I didn't even touch the `TSDL_SpinLock` declaration, so if the indentation is incorrect, it was incorrect all the time.

**Comment by Free-Pascal-meets-SDL-Website** [comment]
Thanks, from my side this is ready for merge now :-). Please just merge, if you agree @suve.

**Comment by suve** [comment]
I took the liberty to rebase the changes on top of latest `master` and fix any indentation issues I've found. If you say it looks okay now, then I'm going to merge it.

**Pull request merged**
